Models/Months.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EducationPlatform_GraduationProject.Models
{
    public class Months
    {
        [Key]
        public int MonthId { get; set; }

        public bool? Jan { get; set; }

        public bool? Feb { get; set; }

        public bool? Mar { get; set; }

        public bool? Apr { get; set; }

        public bool? May { get; set; }

        public bool? Jun { get; set; }

        public bool? Jul { get; set; }

        public bool? Aug { get; set; }

        public bool? Sep { get; set; }

        public bool? Oct { get; set; }

        public bool? Nov { get; set; }

        public bool? Dec { get; set; }
        public Student Student { get; set; }
        [ForeignKey("Student")]
        public int StID { get; set; }
    }
}

Controllers/MonthController.cs
using EducationPlatform_GraduationProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace EducationPlatform_GraduationProject.Controllers
{
    public class MonthController : Controller
    {
        //Api Url
        string Baseurl = "http://localhost:5295/";
        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync($"{Baseurl}api/Months/GetStudentMonths/" + id);
            if (response.IsSuccessStatusCode)
            {
                string Res = await response.Content.ReadAsStringAsync();
                ReceveMonth? contents = JsonConvert.DeserializeObject<ReceveMonth>(Res);
                return View(contents);

            }
            else
            {
                return NotFound("هذا الطالب لم يحجز اي شهر");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ReceveMonth contentWithDetails)
        {            
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage res = client.PutAsJsonAsync("http://localhost:5295/api/Months/updatestudentMonths", contentWithDetails).Result;
                if (res.IsSuccessStatusCode)
                {
                    ViewBag.StudentName = contentWithDetails.StudentName;
                    return RedirectToAction("GetAllStudent", "Teacher" , new {id=1} );
                }
                else
                {

                    return RedirectToAction("Privacy", "Home");
                }

            }
        }
        #endregion
    }
}

Views/Month/Edit.cshtml
@model EducationPlatform_GraduationProject.ViewModels.ReceveMonth

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>ReceveMonth</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Month">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentName" class="control-label"></label>
                <input asp-for="StudentName" class="form-control"  />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="StID" class="control-label"></label>
                <input asp-for="StID" class="form-control"  />
                <span asp-validation-for="StID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Jan" class="control-label"></label>
                <input asp-for="Jan" class="form-control" />
                <span asp-validation-for="Jan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Feb" class="control-label"></label>
                <input asp-for="Feb" class="form-control" />
                <span asp-validation-for="Feb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mar" class="control-label"></label>
                <input asp-for="Mar" class="form-control" />
                <span asp-validation-for="Mar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apr" class="control-label"></label>
                <input asp-for="Apr" class="form-control" />
                <span asp-validation-for="Apr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="May" class="control-label"></label>
                <input asp-for="May" class="form-control" />
                <span asp-validation-for="May" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Jun" class="control-label"></label>
                <input asp-for="Jun" class="form-control" />
                <span asp-validation-for="Jun" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Jul" class="control-label"></label>
                <input asp-for="Jul" class="form-control" />
                <span asp-validation-for="Jul" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aug" class="control-label"></label>
                <input asp-for="Aug" class="form-control" />
                <span asp-validation-for="Aug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sep" class="control-label"></label>
                <input asp-for="Sep" class="form-control" />
                <span asp-validation-for="Sep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Oct" class="control-label"></label>
                <input asp-for="Oct" class="form-control" />
                <span asp-validation-for="Oct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nov" class="control-label"></label>
                <input asp-for="Nov" class="form-control" />
                <span asp-validation-for="Nov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dec" class="control-label"></label>
                <input asp-for="Dec" class="form-control" />
                <span asp-validation-for="Dec" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>